03:31:37 PM:DEBUG [logger_base.py:16] Mensaje a nivel debug
03:31:37 PM:INFO [logger_base.py:17] Mensaje a nivel info
03:31:37 PM:WARNING [logger_base.py:18] Mensaje a nivel warning
03:31:37 PM:ERROR [logger_base.py:19] Mensaje a nivel error
03:31:37 PM:CRITICAL [logger_base.py:20] Mensaje a nivel critical
03:00:45 PM:DEBUG [Persona.py:54] 
            Id persona: 1,
            Nombre: Juan,
            Apellido: Perez,
            Email: jperez@mail.com
        
03:03:45 PM:DEBUG [Persona.py:54] 
            Id persona: 1,
            Nombre: Juan,
            Apellido: Perez,
            Email: jperez@mail.com
        
03:03:45 PM:DEBUG [Persona.py:56] 
            Id persona: None,
            Nombre: Jose,
            Apellido: Lepez,
            Email: ljose@mail.com
        
03:29:59 PM:DEBUG [Conexion.py:25] Conexion Exitosa: <connection object at 0x000002549816CD00; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
03:31:23 PM:DEBUG [Conexion.py:25] Conexion Exitosa: <connection object at 0x00000212CFCFCD00; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
03:31:23 PM:ERROR [Conexion.py:41] Ocurrió un error: 'NoneType' object has no attribute 'cursor'
03:33:41 PM:DEBUG [Conexion.py:25] Conexion Exitosa: <connection object at 0x00000245E735CD00; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
03:33:41 PM:ERROR [Conexion.py:41] Ocurrió un error: 'NoneType' object has no attribute 'cursor'
03:34:03 PM:DEBUG [Conexion.py:25] Conexion Exitosa: <connection object at 0x000001A147B6CD00; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
03:34:03 PM:DEBUG [Conexion.py:38] Se abrio correctamente el cursor:<cursor object at 0x000001A147812CE0; closed: 0>
03:02:31 PM:DEBUG [Conexion.py:25] Conexion Exitosa: <connection object at 0x00000198B4256020; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
03:02:31 PM:DEBUG [Conexion.py:38] Se abrio correctamente el cursor:<cursor object at 0x00000198B6032F80; closed: 0>
03:02:31 PM:DEBUG [persona_dao.py:36] 
            Id persona: 1,
            Nombre: Juan Carlos,
            Apellido: Roldan,
            Email: jcroldan@mail.com
        
03:02:31 PM:DEBUG [persona_dao.py:36] 
            Id persona: 2,
            Nombre: Carla,
            Apellido: Gomez,
            Email: kgomez@mail.com
        
03:02:31 PM:DEBUG [persona_dao.py:36] 
            Id persona: 9,
            Nombre: Carlos,
            Apellido: Lara,
            Email: clara@mail.com
        
03:02:31 PM:DEBUG [persona_dao.py:36] 
            Id persona: 10,
            Nombre: Marcos,
            Apellido: Canto,
            Email: mcanto@mail.com
        
03:02:31 PM:DEBUG [persona_dao.py:36] 
            Id persona: 11,
            Nombre: Marcelo,
            Apellido: Cuenca,
            Email: cuencam@mail.com
        
03:02:31 PM:DEBUG [persona_dao.py:36] 
            Id persona: 12,
            Nombre: Maria,
            Apellido: Esparza,
            Email: mesparza@mail.com
        
03:02:31 PM:DEBUG [persona_dao.py:36] 
            Id persona: 13,
            Nombre: Carlos,
            Apellido: Lara,
            Email: clara@mail.com
        
03:02:31 PM:DEBUG [persona_dao.py:36] 
            Id persona: 14,
            Nombre: Jorge,
            Apellido: Prol,
            Email: jprol@mail.com
        
03:02:31 PM:DEBUG [persona_dao.py:36] 
            Id persona: 15,
            Nombre: Alex,
            Apellido: Rojas,
            Email: arojas@mail.com
        
03:20:08 PM:DEBUG [Conexion.py:25] Conexion Exitosa: <connection object at 0x0000015E1496D250; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
03:20:08 PM:DEBUG [Conexion.py:38] Se abrio correctamente el cursor:<cursor object at 0x0000015E14612F80; closed: 0>
03:20:08 PM:DEBUG [persona_dao.py:39] Persona insertada: 
            Id persona: None,
            Nombre: Pedro,
            Apellido: Romero,
            Email: promero@mail.com
        
03:20:08 PM:DEBUG [persona_dao.py:47] Personas insertadas: 1
03:21:54 PM:DEBUG [Conexion.py:25] Conexion Exitosa: <connection object at 0x000002D2C3E5D250; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
03:21:54 PM:DEBUG [Conexion.py:38] Se abrio correctamente el cursor:<cursor object at 0x000002D2C3B02F80; closed: 0>
03:21:54 PM:DEBUG [persona_dao.py:39] Persona insertada: 
            Id persona: None,
            Nombre: Omero,
            Apellido: Ramos,
            Email: omeror@mail.com
        
03:21:54 PM:DEBUG [persona_dao.py:47] Personas insertadas: 1
03:43:44 PM:DEBUG [Conexion.py:25] Conexion Exitosa: <connection object at 0x00000222253D1140; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
03:43:44 PM:DEBUG [Conexion.py:38] Se abrio correctamente el cursor:<cursor object at 0x0000022225052F80; closed: 0>
03:43:44 PM:DEBUG [persona_dao.py:58] Los objetos eliminados son: 
            Id persona: 13,
            Nombre: None,
            Apellido: None,
            Email: None
        
03:43:44 PM:DEBUG [persona_dao.py:66] Personas eliminadas: 1
03:44:13 PM:DEBUG [Conexion.py:25] Conexion Exitosa: <connection object at 0x000001F90271D140; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
03:44:13 PM:DEBUG [Conexion.py:38] Se abrio correctamente el cursor:<cursor object at 0x000001F9023A2F80; closed: 0>
03:44:13 PM:DEBUG [persona_dao.py:58] Los objetos eliminados son: 
            Id persona: 9,
            Nombre: None,
            Apellido: None,
            Email: None
        
03:44:13 PM:DEBUG [persona_dao.py:66] Personas eliminadas: 1
03:37:16 PM:DEBUG [Conexion.py:38] creación del pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x000001F5E1D7AD10>
03:38:27 PM:DEBUG [Conexion.py:38] creación del pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x00000170FD17AD10>
03:38:27 PM:DEBUG [Conexion.py:20] Conexión obtenida del pool: <connection object at 0x00000170FD43CE10; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
03:38:27 PM:DEBUG [Conexion.py:20] Conexión obtenida del pool: <connection object at 0x00000170FD43CF20; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
03:39:16 PM:DEBUG [Conexion.py:38] creación del pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x000001C3AF6EAC50>
03:39:16 PM:DEBUG [Conexion.py:20] Conexión obtenida del pool: <connection object at 0x000001C3AF98CE10; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
03:39:17 PM:DEBUG [Conexion.py:20] Conexión obtenida del pool: <connection object at 0x000001C3AF98CF20; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
03:39:17 PM:DEBUG [Conexion.py:20] Conexión obtenida del pool: <connection object at 0x000001C3AF98D030; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
